language: python
python:
- '3.6'
install:
- pip install setuptools
script: true
deploy:
  provider: pypi
  user: Mogeko
  password: ${PyPI_PASSWORD}
  on:
    python: 3.6
    tags: true
    branch: master
